[mypy]
check_untyped_defs = True
disallow_untyped_defs = True
show_error_codes = True
show_traceback = True

[mypy-prometheus_client]
ignore_missing_imports = True

[mypy-py_vapid]
ignore_missing_imports = True

[mypy-pywebpush]
ignore_missing_imports = True

[mypy-sygnal.notifications]
disallow_untyped_defs = False

[mypy-sygnal.http]
disallow_untyped_defs = False

[mypy-sygnal.sygnal]
disallow_untyped_defs = False

[mypy-tests.testutils]
disallow_untyped_defs = False
