[tox]
envlist = py, check_codestyle, check_types

[testenv]
usedevelop=true

allowlist_externals = uv

commands =
  uv run coverage run --source=sygnal -m twisted.trial tests
  uv run coverage report --sort=cover
  uv run coverage html

[testenv:check_codestyle]

allowlist_externals = uv

commands =
  uv run ruff sygnal/ tests/ stubs
  uv run black --check --diff sygnal/ tests/ stubs
  uv run isort --check-only --diff sygnal/ tests/ stubs

[testenv:check_types]

allowlist_externals = uv

commands =
  uv run mypy sygnal/ tests/ stubs
